##### Menu
menu:
  首页: /
  文章: /archives
  关于: /about
  RSS订阅: /atom.xml
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- weibo
- category
- tag
- links
- rss

## provide six widgets:category,tag,rss,archive,tagcloud,links.
## modify links in `/layout/_widget/links.ejs`.

#### RSS
rss: atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src:         ## `.svg` and `.png` are recommended,please put image into the theme folder `/dream/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/dream/source/img`.     
apple_icon: img/pacman.jpg ## size:114px*114px,please put image into the theme folder `/dream/source/img`.

#### Author Avatar Picture
author_img_enable: false ## display author avatar picture
dataURI: false
## if the picture's format is dataURI please set the value to true,otherwise set the value to false.
## convert an image into base 64 data URIs http://websemantics.co.uk/online_tools/image_to_data_uri_convertor/ .
author_img_data: ''
## paste the dataURI in ONE LINE and included it by ''.
author_img: img/author.jpg ## size:220px*220px.
## if the picture's format is `.png` or `.jpg`  instead of dataURI,you should set the `dataURI` value to false.

#### Font
ShowCustomFont: false
## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/iceman/source/css`.

#### Toc
toc:
  article: true   ## show contents in article.
  aside: false     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Fancybox
fancybox: false 
## if you use gallery post or want use fancybox please set the value to true.
## if you want use fancybox in ANY post please copy the file `fancybox.js`.
## in theme folder `/iceman/scripts` to your hexo blog folder `../scritps`.

#### Author information
author:
  google_plus:    ## eg:116338260303228776998 for https://plus.google.com/u/0/116338260303228776998
  intro_line1: "没有礁石，就没有美丽的浪花；没有挫折，就没有壮丽的人生！" ## eg: "Hello ,I'm Larry Page in Google."
  intro_line2: "再长的路，一步步也能走完，再短的路，不迈开双脚也无法到达，平凡的脚步也可以走完伟大的行程！" ## eg: "This is my blog,believe it or not."
  weibo:       2583230784     ## e.g. 2583230784 for http://weibo.com/2583230784
  twitter:     idreajay ## e.g. yangjiansky for https://twitter.com/idreajay
  github:      dreajay ## e.g. A-limon for https://github.com/A-limon
  facebook:     ## e.g. dreajay.dai for https://favebook.com/dreajay.dai
  tsina:      2583230784 ## e.g. 1664838973  Your weibo ID,It will be used in share button.

#### Comment
duoshuo: 
  enable: true  ## duoshuo.com
  short_name: dreajaygithubblog  ## duoshuo short name.

#### fork me on github
github:
  enable: false

#### defaultshare button
defaultshare:
  enable: false

#### baidushare button
baidushare:
  enable: false

#### Share button
jiathis:
  enable: true ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1501277 your jiathis ID. 
  tsina: ## e.g. 1664838973 Your weibo id,It will be used in share button.

#### 百度统计
baidu_tongji: 
   enable: true

#### 百度搜索
baidu_search: 
  enable: false
  zhannei: "17834434419516021878"


#### Analytics
google_analytics:
  enable: false
  id:   ## e.g. UA-1766729-8 your google analytics ID.
  site: ## e.g. yangjian.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN

#### 51la Analytics
la51_analytics:
  enable: false
  id:   ## e.g. 17278963 is your 51la analytics ID.

#### Custom Search
google_cse: 
  enable: false
  cx:  ## e.g. 000561263943549425496:mrzrm0gr4kg your Custom Search ID
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---

#### Standard Search
standard_search: 
  engine: 'baidu'  ## possible enum: false/google/baidu. set to false if you want to hide the default search box

#### fotorama in index page
fotorama:
  enable: false ## true to enable fotorama in index page
  fit: 'cover' ## Can be 'contain', 'cover', 'scaledown', 'none'
  nav: 'thumbs' ## Can be 'dots', 'thumbs', false
  transition: 'slide' ## Can be 'slide', 'crossfade', 'dissolve'
  autoplay: false ## Can be true or false
  loop: true ## Can be true or false
  baseurl: '' ## base url will be prefixed to photo url, both show and thumb
  photos:
    - { show: "http://s.fotorama.io/1.jpg", thumb: "http://s.fotorama.io/1.jpg" }
    - "http://s.fotorama.io/2.jpg"
## http://fotorama.io/
